import {AdventureWorld, AdventureProgress} from '../types/game';

export const ADVENTURE_WORLDS: AdventureWorld[] = [
  // === World 1: Counting Meadow (FREE) ===
  {
    id: 'counting-meadow',
    nameKey: 'adventure.worlds.countingMeadow',
    emoji: '🌿',
    theme: 'forest',
    freeLevels: 2,
    levels: [
      {
        id: 'cm-1',
        worldId: 'counting-meadow',
        order: 1,
        nameKey: 'adventure.levels.cm1',
        emoji: '🍄',
        isBonus: false,
        gameMode: 'counting',
        modeLevel: 1,
        problemCount: 5,
        unlockCondition: {type: 'first'},
      },
      {
        id: 'cm-2',
        worldId: 'counting-meadow',
        order: 2,
        nameKey: 'adventure.levels.cm2',
        emoji: '🦋',
        isBonus: false,
        gameMode: 'counting',
        modeLevel: 2,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'cm-1'},
      },
      {
        id: 'cm-3',
        worldId: 'counting-meadow',
        order: 3,
        nameKey: 'adventure.levels.cm3',
        emoji: '🌸',
        isBonus: false,
        gameMode: 'counting',
        modeLevel: 3,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'cm-2'},
      },
      {
        id: 'cm-4',
        worldId: 'counting-meadow',
        order: 4,
        nameKey: 'adventure.levels.cm4',
        emoji: '🐛',
        isBonus: false,
        gameMode: 'counting',
        modeLevel: 4,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'cm-3'},
      },
      {
        id: 'cm-5',
        worldId: 'counting-meadow',
        order: 5,
        nameKey: 'adventure.levels.cm5',
        emoji: '🌻',
        isBonus: false,
        gameMode: 'counting',
        modeLevel: 5,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'cm-4'},
      },
      {
        id: 'cm-6',
        worldId: 'counting-meadow',
        order: 6,
        nameKey: 'adventure.levels.cm6',
        emoji: '🦊',
        isBonus: false,
        gameMode: 'counting',
        modeLevel: 6,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'cm-5'},
      },
      {
        id: 'cm-7',
        worldId: 'counting-meadow',
        order: 7,
        nameKey: 'adventure.levels.cm7',
        emoji: '🦉',
        isBonus: false,
        gameMode: 'counting',
        modeLevel: 7,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'cm-6'},
      },
      {
        id: 'cm-8',
        worldId: 'counting-meadow',
        order: 8,
        nameKey: 'adventure.levels.cm8',
        emoji: '🌳',
        isBonus: false,
        gameMode: 'counting',
        modeLevel: 8,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'cm-7'},
      },
      {
        id: 'cm-bonus-a',
        worldId: 'counting-meadow',
        order: 9,
        nameKey: 'adventure.levels.cmBonusA',
        emoji: '⭐',
        isBonus: true,
        gameMode: 'counting',
        modeLevel: 9,
        problemCount: 5,
        unlockCondition: {type: 'stars', worldId: 'counting-meadow', count: 15},
      },
      {
        id: 'cm-bonus-b',
        worldId: 'counting-meadow',
        order: 10,
        nameKey: 'adventure.levels.cmBonusB',
        emoji: '🏆',
        isBonus: true,
        gameMode: 'counting',
        modeLevel: 10,
        problemCount: 5,
        unlockCondition: {type: 'stars', worldId: 'counting-meadow', count: 20},
      },
    ],
  },

  // === World 2: Addition Island (PREMIUM) ===
  {
    id: 'addition-island',
    nameKey: 'adventure.worlds.additionIsland',
    emoji: '🐳',
    theme: 'ocean',
    freeLevels: 2,
    levels: [
      {
        id: 'ai-1',
        worldId: 'addition-island',
        order: 1,
        nameKey: 'adventure.levels.ai1',
        emoji: '🐚',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 1,
        problemCount: 5,
        unlockCondition: {type: 'first'},
      },
      {
        id: 'ai-2',
        worldId: 'addition-island',
        order: 2,
        nameKey: 'adventure.levels.ai2',
        emoji: '🐟',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 2,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-1'},
      },
      {
        id: 'ai-3',
        worldId: 'addition-island',
        order: 3,
        nameKey: 'adventure.levels.ai3',
        emoji: '🦀',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 3,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-2'},
      },
      {
        id: 'ai-4',
        worldId: 'addition-island',
        order: 4,
        nameKey: 'adventure.levels.ai4',
        emoji: '🐠',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 4,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-3'},
      },
      {
        id: 'ai-5',
        worldId: 'addition-island',
        order: 5,
        nameKey: 'adventure.levels.ai5',
        emoji: '🐙',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 5,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-4'},
      },
      {
        id: 'ai-6',
        worldId: 'addition-island',
        order: 6,
        nameKey: 'adventure.levels.ai6',
        emoji: '🦈',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 6,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-5'},
      },
      {
        id: 'ai-7',
        worldId: 'addition-island',
        order: 7,
        nameKey: 'adventure.levels.ai7',
        emoji: '🐬',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 7,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-6'},
      },
      {
        id: 'ai-8',
        worldId: 'addition-island',
        order: 8,
        nameKey: 'adventure.levels.ai8',
        emoji: '🐳',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 8,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-7'},
      },
      {
        id: 'ai-9',
        worldId: 'addition-island',
        order: 9,
        nameKey: 'adventure.levels.ai9',
        emoji: '🦑',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 9,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-8'},
      },
      {
        id: 'ai-10',
        worldId: 'addition-island',
        order: 10,
        nameKey: 'adventure.levels.ai10',
        emoji: '🏝️',
        isBonus: false,
        gameMode: 'addition',
        modeLevel: 10,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'ai-9'},
      },
      {
        id: 'ai-bonus-a',
        worldId: 'addition-island',
        order: 11,
        nameKey: 'adventure.levels.aiBonusA',
        emoji: '⭐',
        isBonus: true,
        gameMode: 'addition',
        modeLevel: 10,
        problemCount: 5,
        unlockCondition: {type: 'stars', worldId: 'addition-island', count: 20},
      },
      {
        id: 'ai-bonus-b',
        worldId: 'addition-island',
        order: 12,
        nameKey: 'adventure.levels.aiBonusB',
        emoji: '🏆',
        isBonus: true,
        gameMode: 'addition',
        modeLevel: 11,
        problemCount: 5,
        unlockCondition: {type: 'stars', worldId: 'addition-island', count: 25},
      },
    ],
  },

  // === World 3: Subtraction Mountain (PREMIUM) ===
  {
    id: 'subtraction-mountain',
    nameKey: 'adventure.worlds.subtractionMountain',
    emoji: '🚀',
    theme: 'space',
    freeLevels: 2,
    levels: [
      {
        id: 'sm-1',
        worldId: 'subtraction-mountain',
        order: 1,
        nameKey: 'adventure.levels.sm1',
        emoji: '🌙',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 1,
        problemCount: 5,
        unlockCondition: {type: 'first'},
      },
      {
        id: 'sm-2',
        worldId: 'subtraction-mountain',
        order: 2,
        nameKey: 'adventure.levels.sm2',
        emoji: '🚀',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 2,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-1'},
      },
      {
        id: 'sm-3',
        worldId: 'subtraction-mountain',
        order: 3,
        nameKey: 'adventure.levels.sm3',
        emoji: '🪐',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 3,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-2'},
      },
      {
        id: 'sm-4',
        worldId: 'subtraction-mountain',
        order: 4,
        nameKey: 'adventure.levels.sm4',
        emoji: '☄️',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 4,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-3'},
      },
      {
        id: 'sm-5',
        worldId: 'subtraction-mountain',
        order: 5,
        nameKey: 'adventure.levels.sm5',
        emoji: '🛸',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 5,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-4'},
      },
      {
        id: 'sm-6',
        worldId: 'subtraction-mountain',
        order: 6,
        nameKey: 'adventure.levels.sm6',
        emoji: '🌍',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 6,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-5'},
      },
      {
        id: 'sm-7',
        worldId: 'subtraction-mountain',
        order: 7,
        nameKey: 'adventure.levels.sm7',
        emoji: '👽',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 7,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-6'},
      },
      {
        id: 'sm-8',
        worldId: 'subtraction-mountain',
        order: 8,
        nameKey: 'adventure.levels.sm8',
        emoji: '🔭',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 8,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-7'},
      },
      {
        id: 'sm-9',
        worldId: 'subtraction-mountain',
        order: 9,
        nameKey: 'adventure.levels.sm9',
        emoji: '🌌',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 9,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-8'},
      },
      {
        id: 'sm-10',
        worldId: 'subtraction-mountain',
        order: 10,
        nameKey: 'adventure.levels.sm10',
        emoji: '🌠',
        isBonus: false,
        gameMode: 'subtraction',
        modeLevel: 10,
        problemCount: 5,
        unlockCondition: {type: 'previous', levelId: 'sm-9'},
      },
      {
        id: 'sm-bonus-a',
        worldId: 'subtraction-mountain',
        order: 11,
        nameKey: 'adventure.levels.smBonusA',
        emoji: '⭐',
        isBonus: true,
        gameMode: 'subtraction',
        modeLevel: 10,
        problemCount: 5,
        unlockCondition: {
          type: 'stars',
          worldId: 'subtraction-mountain',
          count: 20,
        },
      },
      {
        id: 'sm-bonus-b',
        worldId: 'subtraction-mountain',
        order: 12,
        nameKey: 'adventure.levels.smBonusB',
        emoji: '🏆',
        isBonus: true,
        gameMode: 'subtraction',
        modeLevel: 11,
        problemCount: 5,
        unlockCondition: {
          type: 'stars',
          worldId: 'subtraction-mountain',
          count: 25,
        },
      },
    ],
  },
];

export function getDefaultAdventureProgress(): AdventureProgress {
  const progress: AdventureProgress = {
    version: 1,
    currentWorld: 'counting-meadow',
    worlds: {
      'counting-meadow': {unlocked: true, levels: {}},
      'addition-island': {unlocked: true, levels: {}},
      'subtraction-mountain': {unlocked: true, levels: {}},
    },
  };

  for (const world of ADVENTURE_WORLDS) {
    for (const level of world.levels) {
      const isFirst = level.unlockCondition.type === 'first';
      progress.worlds[world.id].levels[level.id] = {
        unlocked: isFirst,
        completed: false,
        stars: 0,
        bestFirstTry: 0,
        attempts: 0,
      };
    }
  }

  return progress;
}

export function getWorldStars(
  worldId: string,
  progress: AdventureProgress,
): number {
  const world = progress.worlds[worldId as keyof typeof progress.worlds];
  if (!world) return 0;
  return Object.values(world.levels).reduce((sum, l) => sum + l.stars, 0);
}

export function getWorldMaxStars(worldId: string): number {
  const world = ADVENTURE_WORLDS.find(w => w.id === worldId);
  if (!world) return 0;
  return world.levels.length * 3;
}
