/**
 * Bilingual voice script for ElevenLabs generation.
 *
 * Each entry produces 2 audio files: assets/audio/{ro,en}/{id}.mp3
 * Run scripts/gen-voice.mjs with ELEVENLABS_API_KEY to batch-generate.
 *
 * Structure: flat dictionary of { id: {ro, en} } so file naming is consistent.
 */

export interface VoiceEntry {
  id: string;
  ro: string;
  en: string;
  // Optional ElevenLabs voice override per entry; otherwise default per language.
  voiceId?: string;
}

export const VOICE_SCRIPT: VoiceEntry[] = [
  // ── Numbers 0-10 (rostite clar, copilul aude când umple celulele) ──
  {id: 'num_0', ro: 'zero', en: 'zero'},
  {id: 'num_1', ro: 'unu', en: 'one'},
  {id: 'num_2', ro: 'doi', en: 'two'},
  {id: 'num_3', ro: 'trei', en: 'three'},
  {id: 'num_4', ro: 'patru', en: 'four'},
  {id: 'num_5', ro: 'cinci', en: 'five'},
  {id: 'num_6', ro: 'șase', en: 'six'},
  {id: 'num_7', ro: 'șapte', en: 'seven'},
  {id: 'num_8', ro: 'opt', en: 'eight'},
  {id: 'num_9', ro: 'nouă', en: 'nine'},
  {id: 'num_10', ro: 'zece', en: 'ten'},

  // ── Numărare ritmică ──
  {id: 'count_to_5', ro: 'unu, doi, trei, patru, cinci!', en: 'one, two, three, four, five!'},
  {id: 'count_to_10', ro: 'unu, doi, trei, patru, cinci, șase, șapte, opt, nouă, zece!', en: 'one, two, three, four, five, six, seven, eight, nine, ten!'},

  // ── Instrucțiuni per mod (kid-friendly, foarte scurte) ──
  {id: 'instr_counting', ro: 'Apasă căsuțele și numără bilele!', en: 'Tap the boxes and count the dots!'},
  {id: 'instr_addition_easy', ro: 'Mai pune câteva bile!', en: 'Add a few more dots!'},
  {id: 'instr_addition', ro: 'Câte bile sunt în total?', en: 'How many dots in total?'},
  {id: 'instr_subtraction_easy', ro: 'Apasă pe bile să le iei!', en: 'Tap the dots to take them away!'},
  {id: 'instr_subtraction', ro: 'Câte bile rămân?', en: 'How many dots are left?'},
  {id: 'instr_puzzle', ro: 'Câte bile mai trebuie până la zece?', en: 'How many more dots to reach ten?'},

  // ── Feedback corect (8 variante, jucate aleator) ──
  {id: 'fb_correct_1', ro: 'Bravo!', en: 'Yes!'},
  {id: 'fb_correct_2', ro: 'Așa e!', en: "That's right!"},
  {id: 'fb_correct_3', ro: 'Super!', en: 'Awesome!'},
  {id: 'fb_correct_4', ro: 'Foarte bine!', en: 'Very good!'},
  {id: 'fb_correct_5', ro: 'Excelent!', en: 'Excellent!'},
  {id: 'fb_correct_6', ro: 'Genial!', en: 'Great!'},
  {id: 'fb_correct_7', ro: 'Hopa, ce repede!', en: 'Wow, so fast!'},
  {id: 'fb_correct_8', ro: 'Da! Așa!', en: 'Yes! Like that!'},

  // ── Feedback încearcă din nou (5 variante, fără cuvântul „greșit") ──
  {id: 'fb_again_1', ro: 'Aproape!', en: 'Almost!'},
  {id: 'fb_again_2', ro: 'Mai încearcă!', en: 'Try again!'},
  {id: 'fb_again_3', ro: 'Hai, poți!', en: 'Come on, you can!'},
  {id: 'fb_again_4', ro: 'Aproape acolo!', en: 'Almost there!'},
  {id: 'fb_again_5', ro: 'Încă o dată!', en: 'One more time!'},

  // ── Mascotă Zee (intro, reacții, încurajare) ──
  {id: 'zee_greeting', ro: 'Salut! Eu sunt Zee. Hai să ne jucăm cu numerele!', en: "Hi! I'm Zee. Let's play with numbers!"},
  {id: 'zee_cheer', ro: 'Hopa, ce bine ai făcut!', en: 'Wow, you did so well!'},
  {id: 'zee_encourage', ro: 'Te descurci de minune!', en: "You're doing amazing!"},
  {id: 'zee_thinking', ro: 'Hmm, gândește-te puțin...', en: 'Hmm, think for a moment...'},
  {id: 'zee_surprised', ro: 'Oho! Uite ce ai găsit!', en: 'Oho! Look what you found!'},
  {id: 'zee_wave_bye', ro: 'Pa-pa! Ne vedem curând!', en: 'Bye-bye! See you soon!'},

  // ── Onboarding helpers (auto-play la young) ──
  {id: 'welcome', ro: 'Bun venit la Matematica cu Zâmbete!', en: 'Welcome to Math with Smiles!'},
  {id: 'ask_age', ro: 'Câți ani ai?', en: 'How old are you?'},
  {id: 'ask_theme', ro: 'Alege tema preferată!', en: 'Choose your favorite theme!'},

  // ── Intro mini-povești per lume Adventure (~6 sec fiecare) ──
  {id: 'world_counting', ro: 'În Lunca Numerelor numărăm bilele magice. Hai să găsim toate!', en: 'In Counting Meadow we count magic dots. Let\'s find them all!'},
  {id: 'world_addition', ro: 'Pe Insula Adunării punem comori în cufăr. Câte sunt împreună?', en: 'On Addition Island we put treasures in the chest. How many together?'},
  {id: 'world_subtraction', ro: 'Pe Muntele Scăderii eliberăm păsările. Câte rămân?', en: 'On Subtraction Mountain we set birds free. How many are left?'},

  // ── Instrucțiuni tematice pe temă × count (young addition/subtraction) ──
  // Format: instr_{add|sub}_{theme}_{1..4}
  // RO: forme singular/plural (1 = singular, 2-4 = plural)
  // EN: same — "1 rocket" vs "2 rockets"
  // Adunare per temă × count
  {id: 'instr_add_space_1', ro: 'Adaugă 1 rachetă!', en: 'Add 1 more rocket!'},
  {id: 'instr_add_space_2', ro: 'Adaugă 2 rachete!', en: 'Add 2 more rockets!'},
  {id: 'instr_add_space_3', ro: 'Adaugă 3 rachete!', en: 'Add 3 more rockets!'},
  {id: 'instr_add_space_4', ro: 'Adaugă 4 rachete!', en: 'Add 4 more rockets!'},
  {id: 'instr_add_forest_1', ro: 'Adaugă 1 ghindă!', en: 'Add 1 more acorn!'},
  {id: 'instr_add_forest_2', ro: 'Adaugă 2 ghinde!', en: 'Add 2 more acorns!'},
  {id: 'instr_add_forest_3', ro: 'Adaugă 3 ghinde!', en: 'Add 3 more acorns!'},
  {id: 'instr_add_forest_4', ro: 'Adaugă 4 ghinde!', en: 'Add 4 more acorns!'},
  {id: 'instr_add_ocean_1', ro: 'Adaugă 1 peștișor!', en: 'Add 1 more fish!'},
  {id: 'instr_add_ocean_2', ro: 'Adaugă 2 peștișori!', en: 'Add 2 more fish!'},
  {id: 'instr_add_ocean_3', ro: 'Adaugă 3 peștișori!', en: 'Add 3 more fish!'},
  {id: 'instr_add_ocean_4', ro: 'Adaugă 4 peștișori!', en: 'Add 4 more fish!'},
  {id: 'instr_add_farm_1', ro: 'Adaugă 1 morcov!', en: 'Add 1 more carrot!'},
  {id: 'instr_add_farm_2', ro: 'Adaugă 2 morcovi!', en: 'Add 2 more carrots!'},
  {id: 'instr_add_farm_3', ro: 'Adaugă 3 morcovi!', en: 'Add 3 more carrots!'},
  {id: 'instr_add_farm_4', ro: 'Adaugă 4 morcovi!', en: 'Add 4 more carrots!'},
  {id: 'instr_add_candy_1', ro: 'Adaugă 1 bomboană!', en: 'Add 1 more candy!'},
  {id: 'instr_add_candy_2', ro: 'Adaugă 2 bomboane!', en: 'Add 2 more candies!'},
  {id: 'instr_add_candy_3', ro: 'Adaugă 3 bomboane!', en: 'Add 3 more candies!'},
  {id: 'instr_add_candy_4', ro: 'Adaugă 4 bomboane!', en: 'Add 4 more candies!'},
  {id: 'instr_add_unicorn_1', ro: 'Adaugă 1 unicorn!', en: 'Add 1 more unicorn!'},
  {id: 'instr_add_unicorn_2', ro: 'Adaugă 2 unicorni!', en: 'Add 2 more unicorns!'},
  {id: 'instr_add_unicorn_3', ro: 'Adaugă 3 unicorni!', en: 'Add 3 more unicorns!'},
  {id: 'instr_add_unicorn_4', ro: 'Adaugă 4 unicorni!', en: 'Add 4 more unicorns!'},
  {id: 'instr_add_pixel_1', ro: 'Adaugă 1 extraterestru!', en: 'Add 1 more alien!'},
  {id: 'instr_add_pixel_2', ro: 'Adaugă 2 extratereștri!', en: 'Add 2 more aliens!'},
  {id: 'instr_add_pixel_3', ro: 'Adaugă 3 extratereștri!', en: 'Add 3 more aliens!'},
  {id: 'instr_add_pixel_4', ro: 'Adaugă 4 extratereștri!', en: 'Add 4 more aliens!'},
  {id: 'instr_add_slime_1', ro: 'Adaugă 1 bulă!', en: 'Add 1 more bubble!'},
  {id: 'instr_add_slime_2', ro: 'Adaugă 2 bule!', en: 'Add 2 more bubbles!'},
  {id: 'instr_add_slime_3', ro: 'Adaugă 3 bule!', en: 'Add 3 more bubbles!'},
  {id: 'instr_add_slime_4', ro: 'Adaugă 4 bule!', en: 'Add 4 more bubbles!'},
  {id: 'instr_add_kpop_1', ro: 'Adaugă 1 inimă!', en: 'Add 1 more heart!'},
  {id: 'instr_add_kpop_2', ro: 'Adaugă 2 inimi!', en: 'Add 2 more hearts!'},
  {id: 'instr_add_kpop_3', ro: 'Adaugă 3 inimi!', en: 'Add 3 more hearts!'},
  {id: 'instr_add_kpop_4', ro: 'Adaugă 4 inimi!', en: 'Add 4 more hearts!'},
  {id: 'instr_add_monsters_1', ro: 'Adaugă 1 monstru!', en: 'Add 1 more monster!'},
  {id: 'instr_add_monsters_2', ro: 'Adaugă 2 monștri!', en: 'Add 2 more monsters!'},
  {id: 'instr_add_monsters_3', ro: 'Adaugă 3 monștri!', en: 'Add 3 more monsters!'},
  {id: 'instr_add_monsters_4', ro: 'Adaugă 4 monștri!', en: 'Add 4 more monsters!'},
  // Scădere per temă × count
  {id: 'instr_sub_space_1', ro: 'Ia 1 rachetă!', en: 'Take 1 rocket away!'},
  {id: 'instr_sub_space_2', ro: 'Ia 2 rachete!', en: 'Take 2 rockets away!'},
  {id: 'instr_sub_space_3', ro: 'Ia 3 rachete!', en: 'Take 3 rockets away!'},
  {id: 'instr_sub_space_4', ro: 'Ia 4 rachete!', en: 'Take 4 rockets away!'},
  {id: 'instr_sub_forest_1', ro: 'Ia 1 ghindă!', en: 'Take 1 acorn away!'},
  {id: 'instr_sub_forest_2', ro: 'Ia 2 ghinde!', en: 'Take 2 acorns away!'},
  {id: 'instr_sub_forest_3', ro: 'Ia 3 ghinde!', en: 'Take 3 acorns away!'},
  {id: 'instr_sub_forest_4', ro: 'Ia 4 ghinde!', en: 'Take 4 acorns away!'},
  {id: 'instr_sub_ocean_1', ro: 'Ia 1 peștișor!', en: 'Take 1 fish away!'},
  {id: 'instr_sub_ocean_2', ro: 'Ia 2 peștișori!', en: 'Take 2 fish away!'},
  {id: 'instr_sub_ocean_3', ro: 'Ia 3 peștișori!', en: 'Take 3 fish away!'},
  {id: 'instr_sub_ocean_4', ro: 'Ia 4 peștișori!', en: 'Take 4 fish away!'},
  {id: 'instr_sub_farm_1', ro: 'Ia 1 morcov!', en: 'Take 1 carrot away!'},
  {id: 'instr_sub_farm_2', ro: 'Ia 2 morcovi!', en: 'Take 2 carrots away!'},
  {id: 'instr_sub_farm_3', ro: 'Ia 3 morcovi!', en: 'Take 3 carrots away!'},
  {id: 'instr_sub_farm_4', ro: 'Ia 4 morcovi!', en: 'Take 4 carrots away!'},
  {id: 'instr_sub_candy_1', ro: 'Ia 1 bomboană!', en: 'Take 1 candy away!'},
  {id: 'instr_sub_candy_2', ro: 'Ia 2 bomboane!', en: 'Take 2 candies away!'},
  {id: 'instr_sub_candy_3', ro: 'Ia 3 bomboane!', en: 'Take 3 candies away!'},
  {id: 'instr_sub_candy_4', ro: 'Ia 4 bomboane!', en: 'Take 4 candies away!'},
  {id: 'instr_sub_unicorn_1', ro: 'Ia 1 unicorn!', en: 'Take 1 unicorn away!'},
  {id: 'instr_sub_unicorn_2', ro: 'Ia 2 unicorni!', en: 'Take 2 unicorns away!'},
  {id: 'instr_sub_unicorn_3', ro: 'Ia 3 unicorni!', en: 'Take 3 unicorns away!'},
  {id: 'instr_sub_unicorn_4', ro: 'Ia 4 unicorni!', en: 'Take 4 unicorns away!'},
  {id: 'instr_sub_pixel_1', ro: 'Ia 1 extraterestru!', en: 'Take 1 alien away!'},
  {id: 'instr_sub_pixel_2', ro: 'Ia 2 extratereștri!', en: 'Take 2 aliens away!'},
  {id: 'instr_sub_pixel_3', ro: 'Ia 3 extratereștri!', en: 'Take 3 aliens away!'},
  {id: 'instr_sub_pixel_4', ro: 'Ia 4 extratereștri!', en: 'Take 4 aliens away!'},
  {id: 'instr_sub_slime_1', ro: 'Ia 1 bulă!', en: 'Take 1 bubble away!'},
  {id: 'instr_sub_slime_2', ro: 'Ia 2 bule!', en: 'Take 2 bubbles away!'},
  {id: 'instr_sub_slime_3', ro: 'Ia 3 bule!', en: 'Take 3 bubbles away!'},
  {id: 'instr_sub_slime_4', ro: 'Ia 4 bule!', en: 'Take 4 bubbles away!'},
  {id: 'instr_sub_kpop_1', ro: 'Ia 1 inimă!', en: 'Take 1 heart away!'},
  {id: 'instr_sub_kpop_2', ro: 'Ia 2 inimi!', en: 'Take 2 hearts away!'},
  {id: 'instr_sub_kpop_3', ro: 'Ia 3 inimi!', en: 'Take 3 hearts away!'},
  {id: 'instr_sub_kpop_4', ro: 'Ia 4 inimi!', en: 'Take 4 hearts away!'},
  {id: 'instr_sub_monsters_1', ro: 'Ia 1 monstru!', en: 'Take 1 monster away!'},
  {id: 'instr_sub_monsters_2', ro: 'Ia 2 monștri!', en: 'Take 2 monsters away!'},
  {id: 'instr_sub_monsters_3', ro: 'Ia 3 monștri!', en: 'Take 3 monsters away!'},
  {id: 'instr_sub_monsters_4', ro: 'Ia 4 monștri!', en: 'Take 4 monsters away!'},

  // ── Pre-phrase (current state): "You have N {noun}" per theme × N1 (1-4) ──
  // Used right when a young addition/subtraction problem appears.
  {id: 'pre_have_space_1', ro: 'Ai 1 rachetă.', en: 'You have 1 rocket.'},
  {id: 'pre_have_space_2', ro: 'Ai 2 rachete.', en: 'You have 2 rockets.'},
  {id: 'pre_have_space_3', ro: 'Ai 3 rachete.', en: 'You have 3 rockets.'},
  {id: 'pre_have_space_4', ro: 'Ai 4 rachete.', en: 'You have 4 rockets.'},
  {id: 'pre_have_space_5', ro: 'Ai 5 rachete.', en: 'You have 5 rockets.'},
  {id: 'pre_have_forest_1', ro: 'Ai 1 ghindă.', en: 'You have 1 acorn.'},
  {id: 'pre_have_forest_2', ro: 'Ai 2 ghinde.', en: 'You have 2 acorns.'},
  {id: 'pre_have_forest_3', ro: 'Ai 3 ghinde.', en: 'You have 3 acorns.'},
  {id: 'pre_have_forest_4', ro: 'Ai 4 ghinde.', en: 'You have 4 acorns.'},
  {id: 'pre_have_forest_5', ro: 'Ai 5 ghinde.', en: 'You have 5 acorns.'},
  {id: 'pre_have_ocean_1', ro: 'Ai 1 peștișor.', en: 'You have 1 fish.'},
  {id: 'pre_have_ocean_2', ro: 'Ai 2 peștișori.', en: 'You have 2 fish.'},
  {id: 'pre_have_ocean_3', ro: 'Ai 3 peștișori.', en: 'You have 3 fish.'},
  {id: 'pre_have_ocean_4', ro: 'Ai 4 peștișori.', en: 'You have 4 fish.'},
  {id: 'pre_have_ocean_5', ro: 'Ai 5 peștișori.', en: 'You have 5 fish.'},
  {id: 'pre_have_farm_1', ro: 'Ai 1 morcov.', en: 'You have 1 carrot.'},
  {id: 'pre_have_farm_2', ro: 'Ai 2 morcovi.', en: 'You have 2 carrots.'},
  {id: 'pre_have_farm_3', ro: 'Ai 3 morcovi.', en: 'You have 3 carrots.'},
  {id: 'pre_have_farm_4', ro: 'Ai 4 morcovi.', en: 'You have 4 carrots.'},
  {id: 'pre_have_farm_5', ro: 'Ai 5 morcovi.', en: 'You have 5 carrots.'},
  {id: 'pre_have_candy_1', ro: 'Ai 1 bomboană.', en: 'You have 1 candy.'},
  {id: 'pre_have_candy_2', ro: 'Ai 2 bomboane.', en: 'You have 2 candies.'},
  {id: 'pre_have_candy_3', ro: 'Ai 3 bomboane.', en: 'You have 3 candies.'},
  {id: 'pre_have_candy_4', ro: 'Ai 4 bomboane.', en: 'You have 4 candies.'},
  {id: 'pre_have_candy_5', ro: 'Ai 5 bomboane.', en: 'You have 5 candies.'},
  {id: 'pre_have_unicorn_1', ro: 'Ai 1 unicorn.', en: 'You have 1 unicorn.'},
  {id: 'pre_have_unicorn_2', ro: 'Ai 2 unicorni.', en: 'You have 2 unicorns.'},
  {id: 'pre_have_unicorn_3', ro: 'Ai 3 unicorni.', en: 'You have 3 unicorns.'},
  {id: 'pre_have_unicorn_4', ro: 'Ai 4 unicorni.', en: 'You have 4 unicorns.'},
  {id: 'pre_have_unicorn_5', ro: 'Ai 5 unicorni.', en: 'You have 5 unicorns.'},
  {id: 'pre_have_pixel_1', ro: 'Ai 1 extraterestru.', en: 'You have 1 alien.'},
  {id: 'pre_have_pixel_2', ro: 'Ai 2 extratereștri.', en: 'You have 2 aliens.'},
  {id: 'pre_have_pixel_3', ro: 'Ai 3 extratereștri.', en: 'You have 3 aliens.'},
  {id: 'pre_have_pixel_4', ro: 'Ai 4 extratereștri.', en: 'You have 4 aliens.'},
  {id: 'pre_have_pixel_5', ro: 'Ai 5 extratereștri.', en: 'You have 5 aliens.'},
  {id: 'pre_have_slime_1', ro: 'Ai 1 bulă.', en: 'You have 1 bubble.'},
  {id: 'pre_have_slime_2', ro: 'Ai 2 bule.', en: 'You have 2 bubbles.'},
  {id: 'pre_have_slime_3', ro: 'Ai 3 bule.', en: 'You have 3 bubbles.'},
  {id: 'pre_have_slime_4', ro: 'Ai 4 bule.', en: 'You have 4 bubbles.'},
  {id: 'pre_have_slime_5', ro: 'Ai 5 bule.', en: 'You have 5 bubbles.'},
  {id: 'pre_have_kpop_1', ro: 'Ai 1 inimă.', en: 'You have 1 heart.'},
  {id: 'pre_have_kpop_2', ro: 'Ai 2 inimi.', en: 'You have 2 hearts.'},
  {id: 'pre_have_kpop_3', ro: 'Ai 3 inimi.', en: 'You have 3 hearts.'},
  {id: 'pre_have_kpop_4', ro: 'Ai 4 inimi.', en: 'You have 4 hearts.'},
  {id: 'pre_have_kpop_5', ro: 'Ai 5 inimi.', en: 'You have 5 hearts.'},
  {id: 'pre_have_monsters_1', ro: 'Ai 1 monstru.', en: 'You have 1 monster.'},
  {id: 'pre_have_monsters_2', ro: 'Ai 2 monștri.', en: 'You have 2 monsters.'},
  {id: 'pre_have_monsters_3', ro: 'Ai 3 monștri.', en: 'You have 3 monsters.'},
  {id: 'pre_have_monsters_4', ro: 'Ai 4 monștri.', en: 'You have 4 monsters.'},
  {id: 'pre_have_monsters_5', ro: 'Ai 5 monștri.', en: 'You have 5 monsters.'},

  // ── Post-phrase (result): "Great! You have N {noun}!" per theme × answer (1-5) ──
  {id: 'post_great_space_1', ro: 'Bravo! Ai 1 rachetă!', en: 'Great! You have 1 rocket!'},
  {id: 'post_great_space_2', ro: 'Bravo! Ai 2 rachete!', en: 'Great! You have 2 rockets!'},
  {id: 'post_great_space_3', ro: 'Bravo! Ai 3 rachete!', en: 'Great! You have 3 rockets!'},
  {id: 'post_great_space_4', ro: 'Bravo! Ai 4 rachete!', en: 'Great! You have 4 rockets!'},
  {id: 'post_great_space_5', ro: 'Bravo! Ai 5 rachete!', en: 'Great! You have 5 rockets!'},
  {id: 'post_great_forest_1', ro: 'Bravo! Ai 1 ghindă!', en: 'Great! You have 1 acorn!'},
  {id: 'post_great_forest_2', ro: 'Bravo! Ai 2 ghinde!', en: 'Great! You have 2 acorns!'},
  {id: 'post_great_forest_3', ro: 'Bravo! Ai 3 ghinde!', en: 'Great! You have 3 acorns!'},
  {id: 'post_great_forest_4', ro: 'Bravo! Ai 4 ghinde!', en: 'Great! You have 4 acorns!'},
  {id: 'post_great_forest_5', ro: 'Bravo! Ai 5 ghinde!', en: 'Great! You have 5 acorns!'},
  {id: 'post_great_ocean_1', ro: 'Bravo! Ai 1 peștișor!', en: 'Great! You have 1 fish!'},
  {id: 'post_great_ocean_2', ro: 'Bravo! Ai 2 peștișori!', en: 'Great! You have 2 fish!'},
  {id: 'post_great_ocean_3', ro: 'Bravo! Ai 3 peștișori!', en: 'Great! You have 3 fish!'},
  {id: 'post_great_ocean_4', ro: 'Bravo! Ai 4 peștișori!', en: 'Great! You have 4 fish!'},
  {id: 'post_great_ocean_5', ro: 'Bravo! Ai 5 peștișori!', en: 'Great! You have 5 fish!'},
  {id: 'post_great_farm_1', ro: 'Bravo! Ai 1 morcov!', en: 'Great! You have 1 carrot!'},
  {id: 'post_great_farm_2', ro: 'Bravo! Ai 2 morcovi!', en: 'Great! You have 2 carrots!'},
  {id: 'post_great_farm_3', ro: 'Bravo! Ai 3 morcovi!', en: 'Great! You have 3 carrots!'},
  {id: 'post_great_farm_4', ro: 'Bravo! Ai 4 morcovi!', en: 'Great! You have 4 carrots!'},
  {id: 'post_great_farm_5', ro: 'Bravo! Ai 5 morcovi!', en: 'Great! You have 5 carrots!'},
  {id: 'post_great_candy_1', ro: 'Bravo! Ai 1 bomboană!', en: 'Great! You have 1 candy!'},
  {id: 'post_great_candy_2', ro: 'Bravo! Ai 2 bomboane!', en: 'Great! You have 2 candies!'},
  {id: 'post_great_candy_3', ro: 'Bravo! Ai 3 bomboane!', en: 'Great! You have 3 candies!'},
  {id: 'post_great_candy_4', ro: 'Bravo! Ai 4 bomboane!', en: 'Great! You have 4 candies!'},
  {id: 'post_great_candy_5', ro: 'Bravo! Ai 5 bomboane!', en: 'Great! You have 5 candies!'},
  {id: 'post_great_unicorn_1', ro: 'Bravo! Ai 1 unicorn!', en: 'Great! You have 1 unicorn!'},
  {id: 'post_great_unicorn_2', ro: 'Bravo! Ai 2 unicorni!', en: 'Great! You have 2 unicorns!'},
  {id: 'post_great_unicorn_3', ro: 'Bravo! Ai 3 unicorni!', en: 'Great! You have 3 unicorns!'},
  {id: 'post_great_unicorn_4', ro: 'Bravo! Ai 4 unicorni!', en: 'Great! You have 4 unicorns!'},
  {id: 'post_great_unicorn_5', ro: 'Bravo! Ai 5 unicorni!', en: 'Great! You have 5 unicorns!'},
  {id: 'post_great_pixel_1', ro: 'Bravo! Ai 1 extraterestru!', en: 'Great! You have 1 alien!'},
  {id: 'post_great_pixel_2', ro: 'Bravo! Ai 2 extratereștri!', en: 'Great! You have 2 aliens!'},
  {id: 'post_great_pixel_3', ro: 'Bravo! Ai 3 extratereștri!', en: 'Great! You have 3 aliens!'},
  {id: 'post_great_pixel_4', ro: 'Bravo! Ai 4 extratereștri!', en: 'Great! You have 4 aliens!'},
  {id: 'post_great_pixel_5', ro: 'Bravo! Ai 5 extratereștri!', en: 'Great! You have 5 aliens!'},
  {id: 'post_great_slime_1', ro: 'Bravo! Ai 1 bulă!', en: 'Great! You have 1 bubble!'},
  {id: 'post_great_slime_2', ro: 'Bravo! Ai 2 bule!', en: 'Great! You have 2 bubbles!'},
  {id: 'post_great_slime_3', ro: 'Bravo! Ai 3 bule!', en: 'Great! You have 3 bubbles!'},
  {id: 'post_great_slime_4', ro: 'Bravo! Ai 4 bule!', en: 'Great! You have 4 bubbles!'},
  {id: 'post_great_slime_5', ro: 'Bravo! Ai 5 bule!', en: 'Great! You have 5 bubbles!'},
  {id: 'post_great_kpop_1', ro: 'Bravo! Ai 1 inimă!', en: 'Great! You have 1 heart!'},
  {id: 'post_great_kpop_2', ro: 'Bravo! Ai 2 inimi!', en: 'Great! You have 2 hearts!'},
  {id: 'post_great_kpop_3', ro: 'Bravo! Ai 3 inimi!', en: 'Great! You have 3 hearts!'},
  {id: 'post_great_kpop_4', ro: 'Bravo! Ai 4 inimi!', en: 'Great! You have 4 hearts!'},
  {id: 'post_great_kpop_5', ro: 'Bravo! Ai 5 inimi!', en: 'Great! You have 5 hearts!'},
  {id: 'post_great_monsters_1', ro: 'Bravo! Ai 1 monstru!', en: 'Great! You have 1 monster!'},
  {id: 'post_great_monsters_2', ro: 'Bravo! Ai 2 monștri!', en: 'Great! You have 2 monsters!'},
  {id: 'post_great_monsters_3', ro: 'Bravo! Ai 3 monștri!', en: 'Great! You have 3 monsters!'},
  {id: 'post_great_monsters_4', ro: 'Bravo! Ai 4 monștri!', en: 'Great! You have 4 monsters!'},
  {id: 'post_great_monsters_5', ro: 'Bravo! Ai 5 monștri!', en: 'Great! You have 5 monsters!'},

  // ── Onboarding hint when child is idle on setup screen ──
  {id: 'press_play', ro: 'Apasă butonul de play să începi!', en: 'Press the play button to start!'},
  {id: 'lets_play', ro: 'Hai să ne jucăm!', en: "Let's play!"},

  // ── ModeChoice screen (Adventure vs Free Play) ──
  {id: 'mode_question', ro: 'Cum vrei să te joci?', en: 'How do you want to play?'},
  {id: 'mode_adventure', ro: 'Aventură! Mergi pe hartă!', en: 'Adventure! Follow the map!'},
  {id: 'mode_freeplay', ro: 'Joc liber! Alege ce vrei!', en: 'Free play! Choose what you want!'},

  // ── Adventure Map ── world selector narration
  {id: 'choose_world', ro: 'Alege o lume!', en: 'Choose a world!'},
  {id: 'world_counting_meadow', ro: 'Lunca numerelor!', en: 'Counting Meadow!'},
  {id: 'world_addition_island', ro: 'Insula adunării!', en: 'Addition Island!'},
  {id: 'world_subtraction_mountain', ro: 'Muntele scăderii!', en: 'Subtraction Mountain!'},
  {id: 'world_make_ten_beach', ro: 'Plaja lui zece!', en: 'Make 10 Beach!'},
  {id: 'world_doubles_castle', ro: 'Castelul dublurilor!', en: 'Doubles Castle!'},
  {id: 'world_memory_garden', ro: 'Grădina memoriei!', en: 'Memory Garden!'},

  // ── Memory Garden phrases ──
  // Phase intros + per-count success announcements.
  {id: 'mem_watch', ro: 'Privește atent!', en: 'Watch carefully!'},
  {id: 'mem_count', ro: 'Acum tu!', en: 'Now your turn!'},
  {id: 'mem_was_1', ro: 'A fost 1!', en: 'There was 1!'},
  {id: 'mem_was_2', ro: 'Au fost 2!', en: 'There were 2!'},
  {id: 'mem_was_3', ro: 'Au fost 3!', en: 'There were 3!'},
  {id: 'mem_was_4', ro: 'Au fost 4!', en: 'There were 4!'},
  {id: 'mem_was_5', ro: 'Au fost 5!', en: 'There were 5!'},
  {id: 'mem_was_6', ro: 'Au fost 6!', en: 'There were 6!'},
  {id: 'mem_was_7', ro: 'Au fost 7!', en: 'There were 7!'},

  // ── Recompense (achievements, stickers, level complete) ──
  {id: 'reward_sticker', ro: 'Ai un sticker nou!', en: 'You got a new sticker!'},
  {id: 'reward_achievement', ro: 'Realizare nouă deblocată!', en: 'New achievement unlocked!'},
  {id: 'reward_level_perfect', ro: 'Perfect! Trei stele!', en: 'Perfect! Three stars!'},
  {id: 'reward_level_great', ro: 'Foarte bine! Două stele!', en: 'Great job! Two stars!'},
  {id: 'reward_level_good', ro: 'Bravo! O stea câștigată!', en: 'Well done! One star earned!'},
  {id: 'reward_streak', ro: 'Joci de mai multe zile la rând! Bravo!', en: "You're playing many days in a row! Awesome!"},
  {id: 'reward_milestone_10', ro: 'Zece stele! Ești pe drumul cel bun!', en: 'Ten stars! You\'re on the right path!'},
  {id: 'reward_milestone_25', ro: 'Douăzeci și cinci de stele! Continuă așa!', en: 'Twenty-five stars! Keep it up!'},
  {id: 'reward_milestone_50', ro: 'Cincizeci de stele! Ești incredibil!', en: 'Fifty stars! You\'re amazing!'},
  {id: 'reward_milestone_100', ro: 'O sută de stele! Ești campion!', en: 'A hundred stars! You\'re a champion!'},
];

export type VoiceId = (typeof VOICE_SCRIPT)[number]['id'];

export const VOICE_BY_ID: Record<string, VoiceEntry> = Object.fromEntries(
  VOICE_SCRIPT.map(e => [e.id, e]),
);
